# Generated by Django 5.1.7 on 2025-03-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Product View'), ('click', 'Click'), ('order', 'Order Placement')], max_length=50)),
                ('user_id', models.IntegerField(blank=True, help_text='Reference to the CustomUser id if available', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional data as JSON', null=True)),
            ],
        ),
    ]
