# Generated by Django 5.1.7 on 2025-04-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('products', '0002_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_quantity_sold_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('profit', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start', 'category'],
            },
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_quantity_sold_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('profit', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start', 'product'],
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_quantity_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_profit', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('view', 'Product View'), ('click', 'Click'), ('order', 'Order Placement'), ('search', 'Search'), ('cart_add', 'Add to Cart'), ('cart_remove', 'Remove from Cart'), ('checkout', 'Checkout'), ('payment', 'Payment')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type'], name='analytics_a_event_t_a460ec_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user_id'], name='analytics_a_user_id_3326ea_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['timestamp'], name='analytics_a_timesta_aef2a5_idx'),
        ),
        migrations.AddField(
            model_name='categoryperformance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='productperformance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['period_type'], name='analytics_s_period__b6eb09_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['start_date'], name='analytics_s_start_d_483ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['end_date'], name='analytics_s_end_dat_e15b88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesreport',
            unique_together={('period_type', 'start_date', 'end_date')},
        ),
        migrations.AddIndex(
            model_name='categoryperformance',
            index=models.Index(fields=['category'], name='analytics_c_categor_f8581b_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryperformance',
            index=models.Index(fields=['period_start'], name='analytics_c_period__05c13e_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryperformance',
            index=models.Index(fields=['period_end'], name='analytics_c_period__4d1aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryperformance',
            index=models.Index(fields=['total_sales'], name='analytics_c_total_s_fbc426_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryperformance',
            unique_together={('category', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='productperformance',
            index=models.Index(fields=['product'], name='analytics_p_product_6224c9_idx'),
        ),
        migrations.AddIndex(
            model_name='productperformance',
            index=models.Index(fields=['period_start'], name='analytics_p_period__b6d9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='productperformance',
            index=models.Index(fields=['period_end'], name='analytics_p_period__1decd5_idx'),
        ),
        migrations.AddIndex(
            model_name='productperformance',
            index=models.Index(fields=['total_sales'], name='analytics_p_total_s_41251e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productperformance',
            unique_together={('product', 'period_start', 'period_end')},
        ),
    ]
