name: freshk
description: A new Flutter project.
publish_to: "none" # Remove this if you plan to publish your package
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter  # Fix indentation here
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  image_picker: ^1.1.2  # Use this stable version
  qr_flutter: ^4.1.0 
  intl: ^0.19.0 
  uuid: ^3.0.6
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.4
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  app_installer: ^1.3.1
  permission_handler: ^12.0.0+1
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  firebase_analytics: ^11.4.6
  shimmer: ^3.0.0
  device_preview: ^1.2.0


  async: any
  font_awesome_flutter: ^10.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google.png
    - assets/facebook.png
    - assets/allow_location.png
    - assets/successfully_created.png
    - assets/profile_placeholder.png
    - assets/Attijari_bank.png
    - assets/bank.png
    - assets/cash.png
    - assets/icon/check_green.png
    - assets/icon/check_grey.png
    - assets/icon/Confirme_green.png
    - assets/icon/Confirme_grey.png
    - assets/icon/Confirme_red.png
    - assets/icon/delivery_green.png
    - assets/icon/delivery_grey.png
    - assets/icon/delivery_red.png
    - assets/icon/logistics_green.png
    - assets/icon/logistics_grey.png
    - assets/icon/logistics_red.png
    - assets/product/
    - assets/icon/
    - assets/navIcons/apple.png
    - assets/navIcons/leaf.png
    - assets/navIcons/vegetable.png
    - assets/product/
