# Generated by Django 5.1.3 on 2025-06-07 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APKVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version in format X.Y.Z",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Version must be in format X.Y.Z (e.g., 1.0.0)",
                                regex="^\\d+\\.\\d+\\.\\d+$",
                            )
                        ],
                    ),
                ),
                (
                    "apk_file",
                    models.FileField(
                        help_text="APK file for this version", upload_to="apk_files/"
                    ),
                ),
                (
                    "release_notes",
                    models.TextField(
                        blank=True, help_text="What's new in this version"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this version is available for download",
                    ),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        default=False, help_text="Whether this is the latest version"
                    ),
                ),
                (
                    "force_update",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to force users to update to this version",
                    ),
                ),
                (
                    "minimum_supported_version",
                    models.CharField(
                        blank=True,
                        help_text="Minimum version that can update to this version",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 checksum of the APK file",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "APK Version",
                "verbose_name_plural": "APK Versions",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="UpdateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("check", "Update Check"),
                            ("download", "APK Download"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("current_version", models.CharField(blank=True, max_length=20)),
                ("target_version", models.CharField(blank=True, max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Update Log",
                "verbose_name_plural": "Update Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
