# Generated by Django 5.1.7 on 2025-05-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0002_alter_order_options_alter_paymenttransaction_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
