# Generated by Django 5.1.7 on 2025-05-30 15:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_alter_product_options_alter_productcategory_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="minimum_stock",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("10.000"),
                help_text="Minimum stock level for alerts",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0"), message="Minimum stock cannot be negative"
                    )
                ],
            ),
        ),
    ]
