# Generated by Django 5.1.7 on 2025-05-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("products", "0003_product_minimum_stock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventorylog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddIndex(
            model_name="inventorylog",
            index=models.Index(
                fields=["product"], name="inventory_i_product_0d970b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorylog",
            index=models.Index(
                fields=["timestamp"], name="inventory_i_timesta_f735d0_idx"
            ),
        ),
    ]
