version: '3.8'

services:
  # Django web application
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-development-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/freshk_db
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000
      # Twilio is disabled in test mode
      - TWILIO_ENABLED=False
      - TWILIO_ACCOUNT_SID=
      - TWILIO_AUTH_TOKEN=
      - TWILIO_PHONE_NUMBER=
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: gunicorn freshk.wsgi:application --bind 0.0.0.0:8000

  # PostgreSQL database
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=freshk_db
    ports:
      - "5432:5432"

  # pgAdmin (uncomment to use)
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@freshk.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume: 