name: iOS Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        
    - name: Install iOS dependencies
      run: |
        cd mobile
        flutter pub get
        cd ios
        pod install
        
    - name: Build iOS (Debug)
      run: |
        cd mobile
        flutter build ios --debug --no-codesign
        
    - name: Build iOS (Release)
      run: |
        cd mobile
        flutter build ios --release --no-codesign
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-artifacts
        path: mobile/build/ios/
        retention-days: 7
        
    - name: Run tests
      run: |
        cd mobile
        flutter test
        
    - name: Analyze code
      run: |
        cd mobile
        flutter analyze
        
    - name: Check formatting
      run: |
        cd mobile
        dart format --set-exit-if-changed .
        
  # # Optional: Add a job for iOS Simulator testing
  # test-ios-simulator:
  #   runs-on: macos-latest
  #   needs: build-ios
    
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
      
  #   - name: Setup Flutter
  #     uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: '3.19.0'
  #       channel: 'stable'
        
  #   - name: Install iOS dependencies
  #     run: |
  #       cd mobile
  #       flutter pub get
  #       cd ios
  #       pod install
        
  #   - name: Run iOS simulator tests
  #     run: |
  #       cd mobile
  #       flutter test --platform=ios
        
  # # Optional: Add a job for code signing (requires secrets)
  # code-sign-ios:
    runs-on: macos-latest
    needs: build-ios
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        
    - name: Install iOS dependencies
      run: |
        cd mobile
        flutter pub get
        cd ios
        pod install
        
    # Note: Code signing requires proper certificates and provisioning profiles
    # This is commented out as it requires additional setup
    # - name: Build iOS with code signing
    #   run: |
    #     cd mobile
    #     flutter build ios --release
    #   env:
    #     BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
    #     P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
    #     BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
    #     KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
    #     TEAM_ID: ${{ secrets.TEAM_ID }}
    #     BUNDLE_ID: ${{ secrets.BUNDLE_ID }} 